version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "daily"
      time: "10:00"
    open-pull-requests-limit: 300
    assignees: 
    - luke-h1
